// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendaceAppWebApi.Models;

#nullable disable

namespace attendaceAppWebApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230515153802_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("attendaceAppWebApi.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsOnLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69263C63C8674A");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CollegeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeId"));

                    b.Property<string>("CollegeName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CollegeId")
                        .HasName("PK__College__29409519F8AD7213");

                    b.ToTable("College", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CourseDuration")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NumberOfSemesters")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D7187E0F21400");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.CourseSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__CourseSe__C9F49270B5F2E967");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSession", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int")
                        .HasColumnName("CollegeID");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HeadOfDepartment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCD24611304");

                    b.HasIndex("CollegeId");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3ADE9A3C8A");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("SemesterID");

                    b.HasKey("SectionId")
                        .HasName("PK__Section__80EF08920E8588A0");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.SectionStudent", b =>
                {
                    b.Property<int>("SectionStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SectionStudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionStudentId"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("SectionStudentId")
                        .HasName("PK__SectionS__807A9EC7C4E16663");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.ToTable("SectionStudent", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.SectionSubject", b =>
                {
                    b.Property<int>("SectionSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SectionSubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionSubjectId"));

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.HasKey("SectionSubjectId")
                        .HasName("PK__SectionS__5BEE0FE3DBBF5966");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SectionSubject", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SemesterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<int?>("SemesterLengthInMonth")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__043301BD6BB80B4B");

                    b.HasIndex("SessionId");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF766FE5B99");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("GraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RollNumber")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A79D40DED86");

                    b.HasIndex("UserId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("SemesterID");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subject__AC1BA388C5F473A7");

                    b.HasIndex("SemesterId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teacher__EDF259443ACA13A1");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACD1EBFD70");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Attendance", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Section", "Section")
                        .WithMany("Attendances")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Secti__6EF57B66");

                    b.HasOne("attendaceAppWebApi.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Stude__6D0D32F4");

                    b.HasOne("attendaceAppWebApi.Models.Subject", "Subject")
                        .WithMany("Attendances")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Subje__6E01572D");

                    b.HasOne("attendaceAppWebApi.Models.Teacher", "Teacher")
                        .WithMany("Attendances")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Teach__6FE99F9F");

                    b.Navigation("Section");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Course", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Course__Departme__3C69FB99");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.CourseSession", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__CourseSes__Cours__3F466844");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Department", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .HasConstraintName("FK__Departmen__Colle__398D8EEE");

                    b.Navigation("College");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Section", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Section__CourseI__5FB337D6");

                    b.HasOne("attendaceAppWebApi.Models.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Section__Departm__60A75C0F");

                    b.HasOne("attendaceAppWebApi.Models.Semester", "Semester")
                        .WithMany("Sections")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Section__Semeste__619B8048");

                    b.Navigation("Course");

                    b.Navigation("Department");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.SectionStudent", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Section", "Section")
                        .WithMany("SectionStudents")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__SectionSt__Secti__6477ECF3");

                    b.HasOne("attendaceAppWebApi.Models.Student", "Student")
                        .WithMany("SectionStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__SectionSt__Stude__656C112C");

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.SectionSubject", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Section", "Section")
                        .WithMany("SectionSubjects")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK__SectionSu__Secti__68487DD7");

                    b.HasOne("attendaceAppWebApi.Models.Subject", "Subject")
                        .WithMany("SectionSubjects")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__SectionSu__Subje__693CA210");

                    b.HasOne("attendaceAppWebApi.Models.Teacher", "Teacher")
                        .WithMany("SectionSubjects")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__SectionSu__Teach__6A30C649");

                    b.Navigation("Section");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Semester", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.CourseSession", "Session")
                        .WithMany("Semesters")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK__Semester__Sessio__4222D4EF");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Staff", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Department", "Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Staff__Departmen__5BE2A6F2");

                    b.HasOne("attendaceAppWebApi.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Staff__UserID__5CD6CB2B");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Student", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Student__UserID__5535A963");

                    b.Navigation("User");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Subject", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Semester", "Semester")
                        .WithMany("Subjects")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__Subject__Semeste__44FF419A");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Teacher", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Teacher__Departm__5812160E");

                    b.HasOne("attendaceAppWebApi.Models.User", "User")
                        .WithMany("Teachers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Teacher__UserID__59063A47");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.User", b =>
                {
                    b.HasOne("attendaceAppWebApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleID__52593CB8");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.College", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.CourseSession", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Sections");

                    b.Navigation("Staff");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Section", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("SectionStudents");

                    b.Navigation("SectionSubjects");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Semester", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("SectionStudents");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Subject", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("SectionSubjects");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("SectionSubjects");
                });

            modelBuilder.Entity("attendaceAppWebApi.Models.User", b =>
                {
                    b.Navigation("Staff");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
